version: 2

project_name: mclip

before:
  hooks:
    - go mod tidy

brews:
  - name: mclip
    repository:
      owner: thismixer
      name: homebrew-tap
    homepage: "https://github.com/thismixer/MultiClip"
    description: "Clipboard sync between Mac and ArchLinux"
    install: |
      bin.install "mclip"

aurs:
  - name: mclip-bin
    homepage: "https://github.com/thismixer/MultiClip"
    description: "Clipboard sync between Mac and ArchLinux"
    maintainers:
      - "thismixer <thismixer@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY_PATH }}
    git_url: "ssh://aur@aur.archlinux.org/mclip-bin.git"
    optdepends:
      - "wl-clipboard: For Wayland support"
      - "xclip: For X11 support"
    package: |-
      install -Dm755 "./mclip" "${pkgdir}/usr/bin/mclip"

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/mclip/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: "Синхронизация буфера обмена между ArchLinux и macOS."